### ISSUE TITLE
Unsupported Extension Identifiers 

### ISSUE THREAD

**Issue by SSK1981** [april/certainly-something#53] opened 2019-03-24 00:28 UTC
These extension IDs were posted as unsupported:
1.3.6.1.4.1.311.21.7
1.3.6.1.4.1.311.21.10

  Noticed after going to URL https://go.microsoft.com/fwlink/?LinkId=691209 which was to download the Microsoft's Media Creation Tool  in order to make a boot able (backup) USB drive (per decentsecurity.com's "securing-your-computer" recommendation). Strange thing was that I got the message "Hmm. We’re having trouble finding that site - Server not found" type message even though a file successfully downloaded (looks like digitally signed SHA-256 by Microsoft Corporation per file properties). Thus I clicked on the Certainly-Something lock icon on my Firefox Quantum version 66.01 64 bit browser and then saw these extensions IDs were unsupported. Just recently I have been dealing with problems with problematic publisher certificates, slow and unstable computer OS/platform and DNS-ssl network related (e.g. FF browser's Options / network settings using 'Enable DNS over HTTPs' /Mozilla.cloudflare-dns.com) issues on this computer.

**Comment by april** [comment] 2019-03-26 16:50
Hey, thanks @SSK1981. This is a duplicate of #2 and #3, which are already fixed. Once I get a chance to publish the next version of the add-on, they should show up in the viewer.

Thanks!

**Closed by april** 2019-03-26 16:50 UTC

**Comment by SSK1981** [comment] 2019-03-29 21:52
Hi April,

   You got a good product going. Thanks for Certainly Something. I saw one
of your videos where you were being interviewed and remember liking what I
heard you say. Please keep up the good work! You know what?  Ah, I couldn't
wait until April 2nd to reply to your email but you probably have a boy
friend already  plus not sure what city you might live in! :-)  Cute pic
with the war paint under your eyes, but seriously I got so much to learn in
this area of internet cybersecurity and even preventing even my laptop
Windows 10 OS/internet computer from being hacked! Let me ask you a
question that maybe your answer could help me though. Before if UAC were
set on the highest and I see the pop-up dialog box ask me whether to run a
program I clicked (like from the desktop), I would see program's
publisher's certificates of MS Windows software products say "Microsoft
Inc" or something similar, but now I've been seeing the publisher's name
come up as "Microsoft Windows" or "Microsoft LLC" instead of Microsoft
Inc.! Also, UAC was acting super crazy and even though I had set it (the
UAC) to the highest, it would ask me (and then I would change it to bring
it down a notch so that I would not be bothered all the time with UAC and
then UAC would ask if UAC could run. During these times, I would often
times check the file's publisher's certificate (which might refer to just
Microsoft Windows or something related to driver level Microsoft Windows,
Production Level certificate. I checked the site parameter of the
certificate and it mentioned Puerto Rico with a date of I think 2011. Saw
strange certificates - Before, sometimes the time stamp was expired. I
wonder how long it it takes for certificate propagation.
  While I was writing this email, now it seems my UAC is working just fine
as if my computer is hacked or some AI hacking software is actively
adjusting different things on my laptop.  After all, I keep seeing in my
Taskmgr processes run that I terminate - like the Chakra JIT compiler or
nms.exe (re JS) run. I didn't run these. Network settings get changed on my
computer too such as File Sharing from no to yes and Network Discovery gets
turned on.

  Geek Squad not too much help and I don't like having to continually use
up a restore point closer and closer to the present. I run AV software like
Trend Micro and Adlice Diag64 , Roguekiller and the command line version
called Rogue Killer CMD plus other tools like Adware from Malwarebytes and
Mc  Affee amipinkc2.exe -d and running rootkitremover using CMD /D with
extensions ...

   My new HP laptop came with so many holes on the OS network it's becoming
a huge time suck away from using my computer to make money/income for
investing ... Feel like it sometimes but am learning a lot and trying to
keep up with adjusting my maladjusting computer software or hacker or
hackers!

With much regards,
Samuel Katagi

PS: I worked at Symantec as a contractor in the QA I18n group as a QA
software engineer intern some years back. It was fun but I feel like I know
still so little about the field even though I have a MSEE having studied
digital communications and computer engineering!!






Regards,
Samuel Katagi
Be

**Comment by SSK1981** [comment] 2019-03-29 22:08
*Hi April* - *Just in case* -

*   This is not a duplicate email of the email I first sent you regarding
this subject (in reply to your Github status update). Please see below with
attached file. *
