### ISSUE TITLE
Doesn't work on sites using discourse software

### ISSUE THREAD

**Issue by sahsanu** [april/certainly-something#20] opened 2018-09-11 16:09 UTC
Hi,

I'm testing this extension and I tried it on a couple of sites using discourse software like https://meta.discourse.org/ and https://community.letsencrypt.org/ but the extension doesn't work, it only shows a blue banner saying "Please refresh the page and try again.".

I tested it with certainly something 1.1.0, Firefox 62 and on Windows 7, Windows 10 and KDE Neon (Ubuntu 16.04).

Don't know whether it is something you can fix from your side or it is a discourse software issue...

P.D. thank you so much for this extension, I love it ;). 

Cheers,
sahsanu

**Comment by rugk** [comment] 2018-09-11 16:11
So does it only happen on Discourse sites? (Note: I cannot reproduce this.)

**Comment by hardfalcon** [comment] 2018-09-11 16:47
I was able to reproduce this several times on community.letsencrypt.com until I allowed XHR requests to status.io and generic requests to discourse-cdn-sjc1.com in uMatrix.

I've been unable to reproduce this since, even removing the added permissions in uMatrix, closing all tabs and clearing out the browser cache didn't bring the error message back - so I'm not sure if this was related or just a coincidence. I use Firefox 62.0 on Archlinux x86_64 with a bunch of privacy-enhancing browser extensions and I've tightened up a long list of about:config parameters regarding privacy, TLS cipher suites, mixed content, DNS and content prefetching/preloading, etc,  in case it matters.

Also, I noticed that Firefox is complaining about a CPS violation when trying to load some service worker JS file on that page, and it also complains about being unable to send a report about said CSP violation appearently because the report URI is "about:blank" instead of a valid HTTP/HTTPS URI.

**Comment by april** [comment] 2018-09-12 20:50
Hmm, I can't seem to reproduce this issue at all either. It works on both sites I've tried. Do you have any other extensions installed that might interfere with things?

If you can figure out how to make this error happen when starting with a blank profile, that would be hugely helpful for my reproduction.

**Comment by sahsanu** [comment] 2018-09-12 21:32
You are right, seems there is some issue with other extensions I'm using.

I've created a new and clean profile and only installed "certainly something" extension and it works pretty fine in all the sites I've tested. If I install [Quick Dial extension](https://addons.mozilla.org/en-US/firefox/addon/quick-dial/) I get the blue banner on discourse sites. I've also created a new and clean profile, installed certainly something extension and then [Gesturefy](https://addons.mozilla.org/en-US/firefox/addon/gesturefy/) extension and the same issue, blue banner.

I hope this helps.

Thank you

**Comment by april** [comment] 2018-09-12 21:37
And the blue banner persists even if you do a hard refresh of the page?

**Comment by april** [comment] 2018-09-12 21:40
(btw I really appreciate your help on this!)

**Comment by sahsanu** [comment] 2018-09-12 22:12
If I refresh the site using F5 to refresh the site the blue banner persists, If I use Ctrl + Shift + r to refresh the site the extension works as expected showing the right cert info.

**Comment by unit309** [comment] 2018-11-16 20:41
Can't reproduce this on Fennec 63.0.

**Comment by tg-x** [comment] 2018-12-25 18:58
Can't reproduce this on the mentioned sites.
However, I just noticed that it does not work on https://addons.mozilla.org :
the extension icon does not appear and the menu item is disabled

**Comment by april** [comment] 2018-12-25 19:38
All extensions are forbidden from running on addons.mozilla.org for security purposes.

If you go to https://addons.mozilla.org./, you should be able to see it.  :)

**Comment by april** [comment] 2019-03-05 18:09
Closing this because it can't be reproduced.  :)

**Closed by april** 2019-03-05 18:09 UTC
